### ISSUE TITLE
Script to create a journal index gives error

### ISSUE THREAD

**Issue by macmend** [kaiwood/voodoopad-journal#1]
jsCocoaObject_callAsFunction : method Symbol.toPrimitive of object __NSCFString not found — remnant of a split call ?

**Comment by kaiwood** [comment]
@macmend Looks like there was a change in the OS some time ago to make this command no longer work. Thanks for reporting! 

It's fixed in the current version and should work now.

**Comment by macmend** [comment]
Thank you
